# Generated by Django 2.2 on 2020-03-28 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodpost', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodpost',
            name='location_link',
        ),
        migrations.AddField(
            model_name='foodpost',
            name='address',
            field=models.CharField(default='', max_length=300),
        ),
    ]
